### ISSUE TITLE
QR Code Datatype is missing in Umbraco 10

### ISSUE THREAD

**Issue by slag-dev** [sebafelis/RoboLynx.Umbraco.QRCodeGenerator#3]
I have installed the beta version and the QR-Code data type is missing in the latest Umbraco 10.4.2 version.  do you release this package for umbraco 10 or higher?

**Comment by sebafelis** [comment]
Package for Umbraco 10 is released in beta version only (available on NuGet). To release final version I need to first remove ImageSharp.Drawing dependency (still in beta version) and write custom solution to replace this library.

**Comment by MMasey** [comment]
Hey @slag-dev, i'm looking for this kind of functionality for an Umbraco 10 project i'm working on at the moment. I'm happy to try and help with some contributions to get it working if I can. Are you able to provide some more insight into your thoughts on a solution and how you tend to work with the project locally?

**Comment by sebafelis** [comment]
Hi @MMasey, 
To work with the project localy I create separetd copy of respoitory for every Umbraco version (branch name afix correspond umbraco version; u9 - Umbraco 9, u10 - Umbraco 10, etc.). To test that project it's works I create separete solution with test Umbraco project in Visual Sutdio 2022. I have alse added to this solution an existing projects from orginal solution to make work faster and don't littering code shared on Github. In this local project is also script that coping plugin's files to test Umbraco project when project is running. Personaly I use gulp script now, however it can by any other simular solution. If you wont, I can shared you later this test solution in other repository. When you configure a working environment let me know, I write what need to be done.

**Comment by sebafelis** [comment]
Version for Umbraco 10 is released now.

**Comment by MMasey** [comment]
Hey @sebafelis, funnily enough I laterally just jumped back onto the project where I needed this! I has previously moved on to something else entirely, so apologies that I never got around to helping. I'm in the process of getting it set up now, it looks great!

Thanks for you're hard work, I think i must have been your first v10 nuget install! 😀
